### ISSUE TITLE
Raspberry Pi Zero W compatibility

### ISSUE THREAD

**Issue by T-vK** [cjimti/iotwifi#11]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

Hello,
I'm very much interested in seeing this working on a Raspberry Pi Zero W.  
Will you add support for that?

**Comment by cjimti** [comment]
@T-vK A few months ago I had it working on a Pi Zero, however, I don't remember if I had to make any adjustments. I don't see a reason why it would not. Did you run into a problem?

**Comment by T-vK** [comment]
I haven't tried it yet. I just assumed it would only work on the 3B and 3B+. I'll report back when I have tried it.

**Comment by cecchisandrone** [comment]
@T-vK see issue #2. I managed to run on Rpi Zero W, you just need to change the base image to an armv6 one.

**Comment by cjimti** [comment]
@cecchisandrone after your previous bug report I created the image arm32v6-1.0.4. Thanks

@T-vK use the image cjimti/iotwifi:arm32v6-1.0.4

**Comment by T-vK** [comment]
Awesome. :) It would be nice to have this information in the Readme.
