### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by NO-ob** [cjimti/iotwifi#13]
* **I'm submitting a ...**
  - [x? ] bug report
  - [ ] feature request
  - [x ] support request

* **Do you want to request a *feature* or report a *bug*?**
Not sure if a bug or not as i dont know if the pi zero w is supported.

* **What is the current behavior?**
I followed your guide up to this part

docker run --rm --privileged --net host \
      -v $(pwd)/wificfg.json:/cfg/wificfg.json \
      cjimti/iotwifi

When i run this the pi will just spit out loads of lines i ran it for a few minutes and at no point did an access point appear on my phone or laptop so i assume that the pi zero isn't supported i can't open another terminal while it's running as the pi zero has no ethernet so i cant interface with it while that command is running . I would like to ask for you to add pi zero w support 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1.
1.
1.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Device: Pi Zero W
  - OS: Raspbian Stretch Lite

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cjimti** [comment]
@NO-ob using the arm6 image is necessary on the zero and older pies 
cjimti/iotwif:arm32v6-1.0.4
