### ISSUE TITLE
Add Docker Hub auto-builder

### ISSUE THREAD

**Issue by breandan** [cjimti/iotwifi#16]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

Request a feature.

* **What is the current behavior?**

Docker Hub images are [static binaries](https://hub.docker.com/r/cjimti/iotwifi/). It would be nice to support Docker Hub auto-builds, linked to the [Dockerfile](https://github.com/cjimti/iotwifi/blob/master/Dockerfile) and build on Docker Hub via the [cross-build technique](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/).

**Comment by cjimti** [comment]
If I open this project in the future I will consider this.
