### ISSUE TITLE
How do I set a default WiFi network for station mode?

### ISSUE THREAD

**Issue by breandan** [cjimti/iotwifi#17]
I can set a default WiFi SSID and PSK for AP mode, but how do I configure the station mode WiFi credentials?

**Comment by breandan** [comment]
Should I just use the `wifi_supplicant.conf`? This is not described in the readme.

**Comment by cjimti** [comment]
yes wifi_supplicant.conf is the place.
https://wiki.archlinux.org/index.php/WPA_supplicant

**Comment by breandan** [comment]
I'm having some trouble configuring the default network via `wpa_supplicant.conf`. It broadcasts the AP WiFi, but does not connect to the default network, using the same wpa_supplicant configuration that worked previously. I have disabled `wpa_supplicant` using the [readme instructions](https://github.com/cjimti/iotwifi#disable-wpa_supplicant-on-raspberry-pi).

**Comment by breandan** [comment]
Note I am able to connect using the REST interface, but the default `wpa_supplicant.conf` fails to join the network (this is my [`wificfg.json`](https://github.com/duckietown/scripts/blob/f36ccb31eb2f81c1bddf0321bdb51c25dea3dbf6/docs/DuckieOS1-RPI3Bp.sh#L270:L285)).

**Comment by breandan** [comment]
PEBCAK. I forgot to mount the `wpa_supplicant.conf` into the container. Added instructions to the readme in case anyone else forgets to do this...
