### ISSUE TITLE
Cool but why do I need Ethernet

### ISSUE THREAD

**Issue by jbrepogmailcom** [cjimti/iotwifi#29]
This is great tutorial. May I have a suggestion?

This configuration requires additional hardware, an Ethernet cable. It is a bit not logical to deal with WiFi configuration while there is a need for cable.

I would recommend to download all packages first and then turn off the wpa_supplicant. I would also recommend to put all steps into simple shell script, so Raspberry could be configured over ssh and WiFi.

Thanks, Jan

**Comment by cjimti** [comment]
There are no explicit requirements for an ethernet cable, however, this project installs docker images so you need to be connected to the internet somehow. Once you have installed the software you no longer need an internet connection.
