### ISSUE TITLE
dnsmasq resolves any query to IP of uap0

### ISSUE THREAD

**Issue by mateuszdrab** [cjimti/iotwifi#30]
* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
I'd like a new feature to allow specifying upstream DNS server/honouring existing configured DNS servers of wlan0.

* **What is the current behavior?**
dnsmasq resolves any query to IP of uap0, there is no option to specify an upstream server for dnsmasq. I've checked the source code and this seems to be hardcoded.

* **What is the expected behavior?**
I'd expect dnsmasq to either forward to DNS configured in /etc/resolv.conf or honour a "server" entry in the "dnsmasq_cfg" config.

* **What is the motivation / use case for changing the behavior?**
The raspberry PI is supposed to be a router/bridge for the wifi of my dash cam which can't connect to 802.1x networks, the REST API would allow me to easily connect the RPI to new wifi networks or even better, auto connect to open networks any try them. Either way, without a working DNS resolution on the uap0 network, this is not going to proceed anywhere.

* **Please tell us about your environment:**
  
  - Device: Raspberry Pi Zero W
  - OS: Raspbian Stretch

**Comment by cjimti** [comment]
@mateuszdrab see the dnsmasq_cfg section of the configuration, this is where you change this. However, this project is not meant to be a bridge. "The main use case for this project is to reproduce functionality common to devices like Nest or Echo, where the user turns on the device, connects to it and configures it for wifi."
