### ISSUE TITLE
Raspberry Pi 3 Model B+ (New Release March 2018) supported?

### ISSUE THREAD

**Issue by suiluj** [cjimti/iotwifi#6]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Please tell us about your environment:**
  
  - Device: Raspberry Pi 3 Model B+ (Release March 2018)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Is this software working on the new Raspberry Pi 3 Model B+ which released last month?
I want to create a cluster with several raspberry pi and plan to buy the new version.

Thanks for your help and great software.

**Comment by cjimti** [comment]
It should work fine on the new B+. I have a couple coming in next week and will report my results. If you test it before I do I would love to know your findings. However, I don't see a reason for it to fail since the architecture is mostly unchanged.

**Comment by suiluj** [comment]
ah ok thanks. i know most components are the same but because of the new wifi (with ac standard and so on) i was not sure.
i will report my results when i get one of the new raspberry pi 3b+

**Comment by cjimti** [comment]
@suiluj I should have a b+ by Thursday the 12th. Looking forward to testing it. Hope it works for you. I am working on a few improvements for version 2. Ensuring it works on b+ will be part of that.

**Comment by suiluj** [comment]
@cjimti thanks a lot! I really like your special approach with the API for scanning and connecting to wifi by sending and receiving JSON messages. That's very useful in a clustered network with remote control possibilities.
