### ISSUE TITLE
pkill wpa_supplicant

### ISSUE THREAD

**Issue by Elpiojo83** [cjimti/iotwifi#8]
* **I'm submitting a ...**
  - [x] bug report
Strange behaviour on Raspberry Pi 3 B, I need to call these commands after every reboot:

# prevent wpa_supplicant from starting on boot
$ sudo systemctl mask wpa_supplicant.service

# kill any running processes named wpa_supplicant
$ sudo pkill wpa_supplicant

Otherwise I couldn’t connect to the Pi. Which is a little uncomfortable, because if I need to call this commands I could also set the WiFi Credentials.

  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1.
1.
1.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Device:
  - OS:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Elpiojo83** [comment]
OMG Sorry for the mess I didn’t see the prefilled text on my mobile.

**Comment by cjimti** [comment]
@Elpiojo83 no problem. This is not really a bug in this software. pkill should just stop any named process running. `sudo systemctl mask wpa_supplicant.service`  hides the service from the startup process. There are a number of ways to prevent wpa_supplicant from starting, you can also just uninstall it, it all depends on the operating system you are running.
