### ISSUE TITLE
Hide the SSID

### ISSUE THREAD

**Issue by tom472** [cjimti/iotwifi#9]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

Thanks for this Docker Container it's pretty much doing exactly what I need it to do.
However, I am looking to hide the SSID that I am broadcasting with this container but I am a little unsure if that configuration is set via the mounted `wpa_supplicant.conf` file or if it is set via `hostapd`.

If it is done via hostapd - are you reading the conf file from: `/etc/hostapd/hostapd.conf` inside the container?

**Comment by cjimti** [comment]
@tom472 I'm glad to hear that it has been useful to you. The hostapd configuration is generated by the application. I am planning on releasing a version 2 in the next couple of week which will allow more control over the wpa_supplicant, dnsmasq and hostapd along with some iptables support. 

Essentially you need to set ignore_broadcast_ssid=1 for hostapd, however, the current version does not support that, v2 will. Also, it is not supported by all wifi drivers so YMMV. 

I'll tag this request with version 2.

**Comment by tom472** [comment]
@cjimti Awesome thanks for the info/update.
I'll keep my eye out for version 2.

Thanks
